CrowdStrike/caracara

examples/common/example.py

```shell
[main]  INFO    profile include tests: None
[main]  INFO    profile exclude tests: None
[main]  INFO    cli include tests: None
[main]  INFO    cli exclude tests: None
[main]  INFO    running on Python 3.8.9
Run started:2022-06-28 17:30:44.804913
Test results:
Code scanned:
Total lines of code: 0
Run metrics:
Undefined: 0
Low: 0
Medium: 0
High: 0
Undefined: 0
Low: 0
Medium: 0
High: 0
Files skipped (1):
... (No such file or directory)
```
N/A
- Running `examples/get_devices/list_windows_devices.py` in Python 3.8 will error with `ValueError: Can't mix absolute and relative paths`. This is because pre-3.9 the `__file__` global is relative, whereas 3.9+ it is absolute …

Ensure absolute path in example decorator for backwards compatibility

---

caracara/common/policy_wrapper.py

```shell
[main]  INFO    profile include tests: None
[main]  INFO    profile exclude tests: None
[main]  INFO    cli include tests: None
[main]  INFO    cli exclude tests: None
[main]  INFO    running on Python 3.10.5
Run started:2022-07-20 15:33:51.235798
Test results:
Code scanned:
Total lines of code: 0
Run metrics:
Undefined: 0
Low: 0
Medium: 0
High: 0
Undefined: 0
Low: 0
Medium: 0
High: 0
```
- `Policy.dump` claims that it conforms to the CrowdStrike API Spec, but it in the case where `style="prevention"`, it does not conform as doesn't as it doesn't have an `ioa_rule_groups` key. In the future I assume we'll have a proper wrapper for `ioa_rule_groups`, but as a temporary …

Added temporary workaround for storing `ioa_rule_groups` in `Policy`

---

.github/dependabot.yml

Updates dependabot to check GH actions for dependency updates.

Add GitHub actions to dependabot

---

caracara/modules/rtr/__init__.py

Quite simply: we need to be able to access this class for type hinting and integrations. Right now we can't. With this PR, we should be able to 🤞 
This is a very minor fix

Expose RTRBatchSession via __init__.py

---

caracara/modules/hosts/hosts.py
poetry.lock
pyproject.toml

This function in `hosts.py` will allow you to retrieve host data in parallel via a `device_ids` parameter. The `describe_devices` endpoint has been edited to make use of this, and now represents syntactic sugar over `get_device_ids` and `get_device_data`.
This is necessary for any integrations that can take AIDs/Device IDs as an input parameter, but still require the wider device data (such as devices' hostnames) for other reasons.

Add a Device Data Retrieval Function that takes Device IDs as a Parameter

---

caracara/modules/prevention_policies/prevention_policies.py

```shell
[main]  INFO    profile include tests: None
[main]  INFO    profile exclude tests: None
[main]  INFO    cli include tests: None
[main]  INFO    cli exclude tests: None
[main]  INFO    running on Python 3.10.5
Run started:2022-08-05 17:01:08.659167
Test results:
Code scanned:
Total lines of code: 0
Run metrics:
Undefined: 0
Low: 0
Medium: 0
High: 0
Undefined: 0
Low: 0
Medium: 0
High: 0
```
- Bug fix: When calling `query_combined_policies` in `PreventionPoliciesApiModule.describe_policies_raw`, the provided `filters` kwarg is passed as `filters`, when the API actually expects it as `filter`. See below for test script.
Script that shows bug:
```py
from caracara import …
```

Fix typo that causes filters to not work in `PreventionPoliciesApiModule`

---

caracara/common/policy_wrapper.py

- Bug fix: In an earlier PR #32 I added a temporary workaround so `ioa_rule_groups` is still accessible through the `Policy` wrapper, but I accidentally also introduced a bug that dumped this with response policies, when it should only be for prevention policies. This is a quick PR to fix that.

Fix bug that `ioa_rule_groups` is dumped with response policies

---

caracara/modules/hosts/hosts_filters.py

Adds filtering logic to search for only Online or Offline hosts. This avoids the need to use a filter like `LastSeen` to determine which hosts are switched on.

Adds Online/Offline Host Filtering

---

caracara/common/batching.py
caracara/common/pagination.py

This code handles empty `resources` lists when returned erroneously by the API.

Adds some error handling to the batching and pagination backends

---

caracara/common/policy_wrapper.py
poetry.lock
pyproject.toml

This bug fix ensures the `Policy.flat_dump()` will place settings within a key named `settings`, rather than the key name defined in the policy type, so that it can be directly imported to Falcon via the APIs.
This unblocks https://github.com/CrowdStrike/Falcon-Toolkit/pull/12

🐛 Changes the key name to settings in flat_dump

---

caracara/common/constants.py
caracara/common/exceptions.py
caracara/modules/hosts/_data_history.py
caracara/modules/hosts/_online_state.py
caracara/modules/hosts/hosts.py
caracara/modules/hosts/hosts_filters.py
tests/unit_tests/test_hosts.py

```shell
Run started:2023-05-04 20:00:15.160487
Test results:
Code scanned:
Total lines of code: 5694
Total lines skipped (#nosec): 1
Run metrics:
Undefined: 0
Low: 0
Medium: 0
High: 0
Undefined: 0
Low: 0
Medium: 0
High: 0
Files skipped (0):
```
This PR adds a hook to the Falcon API  hosts endpoint `get_online_state` and functionality around this endpoint, including filtering host searches by online state and enriching describe device queries with online state data.
- Progress towards resolving the Falcon-Toolkit issue [Suggestion - add a command that reports the connected hosts.](https://github.com/CrowdStrike/Falcon-Toolkit/issues/42)
- Added `caracara.modules.hosts.get_online_state` to retrieve the online …

[FEATURE] Add ability to filter on host online state

---

caracara/modules/hosts/hosts.py
pyproject.toml
tests/unit_tests/test_hosts.py

```shell
Run started:2023-05-25 13:39:24.885780
Test results:
Code scanned:
Total lines of code: 5937
Total lines skipped (#nosec): 1
Run metrics:
Undefined: 0
Low: 0
Medium: 0
High: 0
Undefined: 0
Low: 0
Medium: 0
High: 0
Files skipped (0):
```
- Bug fix: #99 
- describe_devices() has a new optional parameter that defaults to `False` to specify if you want to enrich the results with the online state of the device. More testing is needed for large environments before setting that parameter to `True`.

[BUGFIX] Remove online state enrichment in describe_devices() by default

---

caracara/modules/rtr/rtr.py
pyproject.toml

This PR introduces a fix that should allow https://github.com/CrowdStrike/Falcon-Toolkit/issues/104 to be fixed in the next build of Falcon Toolkit.

Sets the batch size for RTR PUT files to 100

---

.github/workflows/code-quality.yml
caracara/common/csdialog.py
examples/common/example.py
examples/common/filter_loader.py
poetry.lock
pyproject.toml

Resolves #143
This PR also includes a CrowdStrike-style radio dialog that can be used in other caracara-dependent projects (like Falcon Toolkit) to replace libraries like `bullet` and `pick`.

Migrate from Bullet to Prompt Toolkit

---

caracara/client.py
caracara/common/module.py
caracara/modules/__init__.py
caracara/modules/custom_ioa/custom_ioa.py
caracara/modules/flight_control/flight_control.py
caracara/modules/hosts/hosts.py
caracara/modules/prevention_policies/prevention_policies.py
caracara/modules/response_policies/response_policies.py
caracara/modules/rtr/get_file.py
caracara/modules/rtr/rtr.py
caracara/modules/sensor_download/__init__.py
caracara/modules/sensor_download/sensor_download.py
caracara/modules/sensor_update_policies/sensor_update_policies.py
caracara/modules/users/__init__.py
caracara/modules/users/users.py
poetry.lock
pyproject.toml

> Please review our [Code of Conduct](https://github.com/CrowdStrike/falconpy/CODE_OF_CONDUCT.md) 
> and our [Contribution Guidelines](https://github.com/CrowdStrike/falconpy/CONTRIBUTING.md) before submitting a Pull Request.
>
> REMOVE ALL PULL REQUEST HINTS BEFORE SUBMITTING
>
> Pull Request general description should go here.
> Please fill out all values and then remove any help text before submitting your PR.
> Refer to [this PR](https://github.com/CrowdStrike/falconpy/pull/67) as a reference example!
> Check the values above that match your PR and remove the remaining.
```shell
BANDIT ANALYSIS RESULTS SHOULD BE POSTED
HERE. PLEASE REVIEW CONTRIBUTING.md FOR
MORE DETAILS ON GENERATING BANDIT RESULTS
```
If your PR adds features or functionality, what should be included in the next …

Adds user management module

---

tests/unit_tests/test_custom_ioas.py
tests/unit_tests/test_hosts.py
tests/unit_tests/test_prevention_policies.py
tests/unit_tests/test_response_policies.py

> Check the values above that match your PR and remove the remaining.
```shell
(caracara-py3.11) USER-REDACTED@HOSTNAME-REDACTED tests % bandit -r . --configfile=.bandit
[main]	INFO	Found project level .bandit file: ./.bandit
[utils]	WARNING	Unable to parse config file ./.bandit or missing [bandit] section
[main]	INFO	profile include tests: None
[main]	INFO	profile exclude tests: B101
[main]	INFO	cli include tests: None
[main]	INFO	cli exclude tests: None
[main]	INFO	using config: .bandit
[main]	INFO	running on Python 3.11.9
Run started:2024-10-17 14:55:08.937788
Test results:
Code scanned:
Total lines of code: 1445
Run metrics:
Undefined: 0
Low: 0
Medium: 0
High: 0
Undefined: 0 …
```

Update unit tests' mock auth objects to use auto-speccing

---

caracara/modules/custom_ioa/custom_ioa.py
caracara/modules/custom_ioa/rules.py
tests/unit_tests/test_custom_ioas.py

```shell
(caracara-py3.11) redacted@redacted caracara-fork % bandit -r caracara
[main]	INFO	profile include tests: None
[main]	INFO	profile exclude tests: None
[main]	INFO	cli include tests: None
[main]	INFO	cli exclude tests: None
[main]	INFO	running on Python 3.11.9
[manager]	WARNING	Test in comment: The is not a test name or id, ignoring
[manager]	WARNING	Test in comment: password is not a test name or id, ignoring
[manager]	WARNING	Test in comment: infected is not a test name or id, ignoring
[manager]	WARNING	Test in comment: is is not a test name or id, ignoring
[manager]	WARNING	Test in comment: generic is not a test name or id, ignoring
[manager]	WARNING	Test in comment: and is not a test name or id, ignoring
[manager]	WARNING	Test in comment: always is not a test name or id, …
```

Fixes handling of Custom IOA Rule Group Versioning

---

caracara/modules/custom_ioa/custom_ioa.py
tests/unit_tests/test_custom_ioas.py

```shell
(caracara-py3.11) redacted@redacted tests % bandit -r . -s B101
[main]	INFO	Found project level .bandit file: ./.bandit
[utils]	WARNING	Unable to parse config file ./.bandit or missing [bandit] section
[main]	INFO	profile include tests: None
[main]	INFO	profile exclude tests: None
[main]	INFO	cli include tests: None
[main]	INFO	cli exclude tests: B101
[main]	INFO	running on Python 3.11.9
Run started:2024-10-25 11:47:03.460315
Test results:
Code scanned:
Total lines of code: 1586
Run metrics:
Undefined: 0
Low: 0
Medium: 0
High: 0
Undefined: 0
Low: 0
Medium: 0
High: 0
Files skipped (0):
```
- Fixes a bug in rule creation for an IoaRuleGroup which results in newly created …

Fixes rule group addition in IoaRuleGroup._update_create_delete

---

caracara/modules/custom_ioa/rules.py
tests/unit_tests/test_custom_ioas.py

Fixed a bug causing AttributeErrors when accessing cloud fields of `IoaRuleGroup` and `CustomIoaRule` objects.
- Bug fix: Fixes #213 by properly initializing all attributes of `IoaRuleGroup` and `CustomIoaRule` objects during `__init__`
This does not attempt to separate local instances of the objects from clouded instances.
While this prevents a call to e.g. `rule.deleted` from raising an exception, the property is not meaningful on local (to be created in the cloud) objects. I think it's worth considering whether keeping the current behaviour of throwing an error in these cases would be preferable. If so, `__repr__` can be fixed by changing its functionality in the case of local objects.

Fixes attribute errors in the Custom IOA module

---

caracara/client.py
examples/config.example.yml

This update enables support for FalconPy native logging.
```shell
[main]	INFO	running on Python 3.13.0
Run started:2024-11-01 07:57:30.838541
Test results:
Code scanned:
Total lines of code: 5563
Total lines skipped (#nosec): 1
Run metrics:
Undefined: 0
Low: 0
Medium: 0
High: 0
Undefined: 0
Low: 0
Medium: 0
High: 0
Files skipped (0):
```
Adds support for FalconPy debugging-related constructor keywords provided by the OAuth2 object.
- New keyword arguments: 
- `debug`
- `debug_record_count`
- `sanitize_log`
* `client.py`
Demonstrates how to add these values to a configuration profile stored within `config.yml`.
* `examples/config.example.yml`

Add FalconPy native logging support

---

caracara/client.py
caracara/modules/rtr/get_file.py
examples/common/example.py
examples/config.example.yml
examples/rtr/download_event_log.py
examples/rtr/queue_command.py
pyproject.toml

This pull request implements the following:
* Adds the ability to define a default example profile in `config.yml`.
* Adds the ability to define global example settings, as opposed to per profile example settings.  Per profile settings override global settings.
* Adds support for the FalconPy [Environment](https://www.falconpy.io/Usage/Authenticating-to-the-API.html#environment-authentication) and [Context](https://www.falconpy.io/Usage/Authenticating-to-the-API.html#context-authentication) Authentication mechanisms.
* Resolves a filter bug within the _queue_command_ example.
* Resolves a filter bug within the _download_event_log_ example.
* Resolves a bug related to archive extraction within the RTR module (`get_file.py`).
```shell
[main]	INFO	running on Python 3.13.0
Run …
```

Add Environment and Context authentication support, default example profiles and global example settings

---

poetry.lock
pyproject.toml

This PR includes a dependency bump and an overall shift to Version 1.0.0.
The reason to move to version 1 is that Poetry treats versions starting with 0.x differently, which has caused some issues with version control. From V1 we'll work to fully adhere to SemVer, such that only breaking or extremely significant changes will warrant a major version bump. This will additionally assist with dependency management downstream.

Bumps dependencies and version to 1.0.0
